# Node.js Express Web App to Linux on Azure
# Build a Node.js Express app and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
name: $(Date:yyyyMMdd)$(Rev:.r)
parameters:
  - name: appName
    displayName: Application Name
    type: string
  - name: environment
    displayName: Environment for this deployment
    type: string
  - name: location
    displayName: Location of deployed resources
    type: string
  - name: dbUser
    displayName: Username for admin user on PostgreSQL Database
    type: string

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '4c485bf3-112c-4704-9944-e819f2ec7392'
  
  # Environment name
  environmentName: '$(parameters.AppName)-$(parameters.environment)-$(parameters.location)-app'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
      
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - task: CopyFiles@2
      displayName: 'Copy infrastructure code to $(Build.ArtifactStagingDirectory)/infra'
      inputs:
        contents: 'infra/**'
        targetFolder: $(Build.ArtifactStagingDirectory)/infra
    
    - task: Bash@3
      displayName: 'Execute the build script'
      inputs:
        targetType: 'inline'
        workingDirectory: '$(Build.SourcesDirectory)/infra'
        script: |
        chmod +x build.sh
        ./build.sh     
      env:
        APPNAME: ${{ parameters.appName }}
        ENVIRONMENT: ${{ parameters.environment }}
        LOCATION: ${{ parameters.location }}
        DBUSER: ${{ parameters.dbUser }}
        dbPassword: $(dbPassword)
        DEPLOYMENT_FILE_PATH: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip   

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)/drop/$(Build.BuildId).zip'
        artifactName: drop

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)/infra
        artifactName: infra

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: $(environmentName)
    pool: 
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps: 
          - task: AzureCLI@2
            displayName: Deploy Infrastructure Components
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: bash
              scriptLocation: inlineScript
              workingDirectory: $(Pipeline.Workspace)/infra/infra
              inlineScript: |
                chmod +x deploy.sh
                ./deploy.sh
            env:
              APPNAME: ${{ parameters.appName }}
              ENVIRONMENT: ${{ parameters.environment }}
              LOCATION: ${{ parameters.location }}
              DBUSER: ${{ parameters.dbUser }}
              dbPassword: $(dbPassword)
              DEPLOYMENT_FILE_PATH: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
